AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  WLLM-ML

  SAM Template for WLLM-ML with image input for Lambda.

Globals:
  Function:
    Timeout: 10
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true

Resources:
  WLLMCosinePredictionHelper:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: Lambda.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Events:
        WLLM-PredictEvent:
          Type: Api
          Properties:
            Path: /predict
            Method: post
            RequestParameters:
              - method.request.header.Content-Type: true
      Environment:
        Variables:
          S3_BUCKET: "wholookslikeme"
      Policies:
        - AmazonS3ReadOnlyAccess
        - Statement:
            Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:DeleteObject
            Resource:
              Fn::Sub: arn:aws:s3:::${S3_BUCKET}/*

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'

Outputs:
  PredictApi:
    Description: API Gateway endpoint URL for the prediction Lambda function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/predict/"
  PredictFunction:
    Description: Prediction Lambda Function ARN
    Value: !GetAtt WLLMCosinePredictionHelper.Arn
  PredictFunctionIamRole:
    Description: IAM Role created for the Prediction Lambda function
    Value: !GetAtt WLLMCosinePredictionHelperRole.Arn
